# Form implementation generated from reading ui file 'dizainas.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 369)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pirmas_mygtukas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pirmas_mygtukas.setGeometry(QtCore.QRect(60, 140, 75, 24))
        self.pirmas_mygtukas.setObjectName("pirmas_mygtukas")
        self.antras_mygtukas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.antras_mygtukas.setGeometry(QtCore.QRect(160, 140, 75, 24))
        self.antras_mygtukas.setObjectName("antras_mygtukas")
        self.trecias_mygtukas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.trecias_mygtukas.setGeometry(QtCore.QRect(260, 140, 71, 21))
        self.trecias_mygtukas.setObjectName("trecias_mygtukas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pirmas_mygtukas.setText(_translate("MainWindow", "Pirmas"))
        self.antras_mygtukas.setText(_translate("MainWindow", "Antras"))
        self.trecias_mygtukas.setText(_translate("MainWindow", "Trečias"))
