# Form implementation generated from reading ui file 'last_scraper.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nuoroda = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nuoroda.setGeometry(QtCore.QRect(30, 200, 731, 41))
        self.nuoroda.setObjectName("nuoroda")
        self.label_nuoroda = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_nuoroda.setGeometry(QtCore.QRect(280, 120, 351, 21))
        self.label_nuoroda.setObjectName("label_nuoroda")
        self.pateikti = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pateikti.setGeometry(QtCore.QRect(330, 300, 75, 24))
        self.pateikti.setObjectName("pateikti")
        self.rezultatas = QtWidgets.QLabel(parent=self.centralwidget)
        self.rezultatas.setGeometry(QtCore.QRect(160, 430, 441, 16))
        self.rezultatas.setText("")
        self.rezultatas.setObjectName("rezultatas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_nuoroda.setText(_translate("MainWindow", "Įkelkite norimo tinklapio nuorodą"))
        self.pateikti.setText(_translate("MainWindow", "Pateikti"))
