# Form implementation generated from reading ui file 'task_3.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.email_result = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.email_result.setGeometry(QtCore.QRect(70, 100, 113, 22))
        self.email_result.setObjectName("email_result")
        self.label_email = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(210, 100, 71, 21))
        self.label_email.setObjectName("label_email")
        self.psw_result = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.psw_result.setGeometry(QtCore.QRect(70, 160, 113, 22))
        self.psw_result.setObjectName("psw_result")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 160, 71, 16))
        self.label.setObjectName("label")
        self.info_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(70, 50, 201, 21))
        self.info_label.setObjectName("info_label")
        self.enter_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.enter_button.setGeometry(QtCore.QRect(70, 230, 75, 24))
        self.enter_button.setObjectName("enter_button")
        self.notification = QtWidgets.QLabel(parent=self.centralwidget)
        self.notification.setGeometry(QtCore.QRect(60, 340, 431, 21))
        self.notification.setText("")
        self.notification.setObjectName("notification")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_email.setText(_translate("MainWindow", "Email"))
        self.label.setText(_translate("MainWindow", "Password"))
        self.info_label.setText(_translate("MainWindow", "Please enter email and password"))
        self.enter_button.setText(_translate("MainWindow", "Enter"))
