# Form implementation generated from reading ui file 'task_2.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vardas = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.vardas.setGeometry(QtCore.QRect(50, 150, 113, 22))
        self.vardas.setText("")
        self.vardas.setObjectName("vardas")
        self.pavarde = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pavarde.setGeometry(QtCore.QRect(50, 220, 113, 22))
        self.pavarde.setText("")
        self.pavarde.setObjectName("pavarde")
        self.gimimo_metai = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.gimimo_metai.setGeometry(QtCore.QRect(50, 280, 113, 22))
        self.gimimo_metai.setText("")
        self.gimimo_metai.setObjectName("gimimo_metai")
        self.ivesti_varda = QtWidgets.QLabel(parent=self.centralwidget)
        self.ivesti_varda.setGeometry(QtCore.QRect(210, 150, 141, 21))
        self.ivesti_varda.setObjectName("ivesti_varda")
        self.ivesti_pavarde = QtWidgets.QLabel(parent=self.centralwidget)
        self.ivesti_pavarde.setGeometry(QtCore.QRect(210, 220, 141, 21))
        self.ivesti_pavarde.setObjectName("ivesti_pavarde")
        self.ivesti_gimimo_metus = QtWidgets.QLabel(parent=self.centralwidget)
        self.ivesti_gimimo_metus.setGeometry(QtCore.QRect(210, 280, 141, 21))
        self.ivesti_gimimo_metus.setObjectName("ivesti_gimimo_metus")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 80, 381, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pateikti = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pateikti.setGeometry(QtCore.QRect(60, 360, 75, 24))
        self.pateikti.setObjectName("pateikti")
        self.rezultatas = QtWidgets.QLabel(parent=self.centralwidget)
        self.rezultatas.setGeometry(QtCore.QRect(50, 60, 261, 31))
        self.rezultatas.setText("")
        self.rezultatas.setObjectName("rezultatas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ivesti_varda.setText(_translate("MainWindow", "Įveskite varda"))
        self.ivesti_pavarde.setText(_translate("MainWindow", "Įveskite pavardę"))
        self.ivesti_gimimo_metus.setText(_translate("MainWindow", "Įveskite gimimo metus"))
        self.pateikti.setText(_translate("MainWindow", "Pateikti"))
