# Form implementation generated from reading ui file 'Task3Web.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 259)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Input_web = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Input_web.setGeometry(QtCore.QRect(20, 30, 113, 22))
        self.Input_web.setObjectName("Input_web")
        self.Text = QtWidgets.QLabel(parent=self.centralwidget)
        self.Text.setGeometry(QtCore.QRect(170, 30, 211, 141))
        self.Text.setText("")
        self.Text.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.Text.setWordWrap(True)
        self.Text.setObjectName("Text")
        self.Email_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Email_label.setGeometry(QtCore.QRect(30, 10, 49, 16))
        self.Email_label.setObjectName("Email_label")
        self.Start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(30, 60, 75, 24))
        self.Start.setObjectName("Start")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 424, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Email_label.setText(_translate("MainWindow", "WebLink"))
        self.Start.setText(_translate("MainWindow", "Start"))
