# Form implementation generated from reading ui file 'designexam.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scraper_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.scraper_name.setGeometry(QtCore.QRect(0, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.scraper_name.setFont(font)
        self.scraper_name.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.scraper_name.setMouseTracking(False)
        self.scraper_name.setObjectName("scraper_name")
        self.welcome_notice = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.welcome_notice.setGeometry(QtCore.QRect(160, 10, 501, 71))
        self.welcome_notice.setObjectName("welcome_notice")
        self.Instructions = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.Instructions.setGeometry(QtCore.QRect(160, 110, 501, 141))
        self.Instructions.setObjectName("Instructions")
        self.paste_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.paste_label.setGeometry(QtCore.QRect(20, 330, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.paste_label.setFont(font)
        self.paste_label.setObjectName("paste_label")
        self.enter_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.enter_button.setGeometry(QtCore.QRect(370, 380, 75, 24))
        self.enter_button.setObjectName("enter_button")
        self.url_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.url_field.setGeometry(QtCore.QRect(160, 330, 501, 21))
        self.url_field.setObjectName("url_field")
        self.notification = QtWidgets.QLabel(parent=self.centralwidget)
        self.notification.setGeometry(QtCore.QRect(178, 460, 501, 16))
        self.notification.setText("")
        self.notification.setObjectName("notification")
        self.found = QtWidgets.QLabel(parent=self.centralwidget)
        self.found.setGeometry(QtCore.QRect(150, 500, 501, 20))
        self.found.setText("")
        self.found.setObjectName("found")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.scraper_name.setText(_translate("MainWindow", "SAMI- Scraper"))
        self.welcome_notice.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-style:italic;\">Welcome to SAMI- Scraper! This tool helps you find the best deals online. Simply enter the product URL and let SAMI- Scraper! do the work! 🛍️</span></p></body></html>"))
        self.Instructions.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">This tool helps you gather information about ads on elenta.lt. To get started:</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" font-style:italic;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Go to elenta.lt</span></li>\n"
"<li style=\" font-weight:700; font-style:italic;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select the category you\'re interested in.</li>\n"
"<li style=\" font-weight:700; font-style:italic;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Copy url and paste it in the field below.</li></ol>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Once you\'ve provided the category, the scraper will extract the name and price of every ad in that category. Happy scraping!</span></p></body></html>"))
        self.paste_label.setText(_translate("MainWindow", "Paste URL here"))
        self.enter_button.setText(_translate("MainWindow", "Enter"))
